### ISSUE TITLE
Use G1 garbage collector

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera-cmd#1]
cf https://dzone.com/articles/choosing-the-right-gc

**Comment by hanslovsky** [comment]
I will not include this in the next release as this should probably wait for https://github.com/scijava/jgo/pull/58

**Comment by hanslovsky** [comment]
@igorpisarev, once https://github.com/scijava/jgo/pull/58 is merged, [`launch_paintera`](https://github.com/saalfeldlab/paintera-cmd/blob/b2d58bfc465afd8b6458eac98b1d24aa87c29f05/paintera/__init__.py#L39) should handle setting  the appropriate garbage collector, i.e.
 1. If any garbage collector is specified (probably best to check if any of the legal gc settings is already present), do not do anything,
 2. Add `-XX:+UseG1GC` flag (and `--` if necessary) otherwise.

**Comment by igorpisarev** [comment]
That's cool! I haven't tried the G1 garbage collector so it would be interesting to see how it performs. I just read that it was made the default in Java 9+, so it seems that we won't need to set it explicitly when we update to Java 13.

**Comment by cmhulbert** [comment]
Since version 0.26.0, Paintera target Java 11. As such, this can be closed.
