### ISSUE TITLE
Cannot specify any arguments on Windows

### ISSUE THREAD

**Issue by igorpisarev** [saalfeldlab/paintera-cmd#2]
I installed Paintera 0.20.0 through conda on Windows, and if I run just `paintera` it works and opens the project selection dialog, but I cannot run it with any arguments such as:

```
C:\>paintera D:\data\paintera-project

ERROR 2019-09-20 13:58:01,078: list index out of range
  File "C:\ProgramData\Miniconda3\lib\site-packages\jgo\jgo.py", line 258, in jgo_main
    completed_process = run(parser, argv=argv, stdout=stdout, stderr=stderr)
  File "C:\ProgramData\Miniconda3\lib\site-packages\jgo\jgo.py", line 533, in run
    repositories[repository.split('=')[0]] = repository.split('=')[1]
usage: paintera [-v] [-u] [-U] [-m] [--ignore-jgorc] [--link-type type] [--additional-jars jar [jar ...]] [--additional-endpoints endpoint [endpoint ...]] [JVM_OPTIONS [JVM_OPTIONS ...]] <endpoint> [main-args]
```

The same error occurs if I try other arguments like `--add-n5-container`. Interestingly, `paintera --help` works fine and outputs the usage.

Not sure if it's an issue with the scripts in this repo or with jgo.

**Comment by hanslovsky** [comment]
Can you try with a relative path? Maybe the `D:\...` is not handled properly in the python parser. What version of jgo are you using? And can you try `paintera -- D:\data\paintera-project`?

**Comment by igorpisarev** [comment]
This works now after updating paintera to 0.21.0 and jgo to 0.5.0.
